[package]
name = "agave-exit-slot"
version = "0.1.0"
edition = "2024"

[dependencies]
"agave-validator" = {version = "3.0.14"}
"tokio" = { version = "1.28", features = ["full"] }
"solana-rpc-client" =  {version = "3.0.14"}